# Generated by Django 5.1.4 on 2026-09-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('subtitle', models.CharField(help_text='One line describing what it is.', max_length=200)),
                ('summary', models.TextField(help_text='Short paragraph used on project cards.')),
                ('project_type', models.CharField(choices=[('web_app', 'Web Application'), ('api', 'API'), ('ai', 'AI Application'), ('tool', 'Tool'), ('other', 'Other')], default='web_app', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('is_solo', models.BooleanField(default=True, help_text='Uncheck for team projects; then fill in your role.')),
                ('role', models.CharField(blank=True, help_text='Your specific contribution. Required for team projects.', max_length=200)),
                ('problem', models.TextField(blank=True, help_text='What problem it solves and why.')),
                ('solution', models.TextField(blank=True, help_text='The approach taken.')),
                ('architecture', models.TextField(blank=True, help_text='How a request flows through the system.')),
                ('challenges', models.TextField(blank=True, help_text='The hardest problem and how it was solved.')),
                ('lessons', models.TextField(blank=True, help_text='What working on this taught you.')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True, help_text='Live demo. The button is hidden while empty.')),
                ('video_url', models.URLField(blank=True, help_text='YouTube URL. An embedded player appears once this is set.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('accent_label', models.CharField(blank=True, help_text='Small label on the card, e.g. "E-commerce".', max_length=40)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured projects appear on the home page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('category', models.CharField(choices=[('language', 'Language'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('tool', 'Tool'), ('service', 'External Service')], default='tool', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Description for screen readers. Falls back to the caption.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.technology'),
        ),
    ]
