# Generated by Django 5.1.4 on 2026-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('display_name', models.CharField(help_text='Name shown in the hero and browser tab.', max_length=120)),
                ('title', models.CharField(help_text='Professional title, e.g. "Software Engineer".', max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(help_text='Public contact address.', max_length=254)),
                ('tagline', models.CharField(blank=True, help_text='Short line under the name in the hero.', max_length=200)),
                ('hero_intro', models.TextField(blank=True, help_text='One or two sentences in the hero.')),
                ('availability', models.CharField(blank=True, help_text='e.g. "Open to remote, hybrid, and onsite roles". Hidden when empty.', max_length=160)),
                ('about_short', models.TextField(blank=True, help_text='Condensed about text for the home page.')),
                ('about_long', models.TextField(blank=True, help_text='Full about text for the about page. Blank lines separate paragraphs.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='PDF resume. The download button is hidden while this is empty.', null=True, upload_to='resume/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('leetcode_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('meta_description', models.CharField(blank=True, help_text='Search result and social preview description.', max_length=180)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
