# Generated by Django 5.1.4 on 2026-09-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=160)),
                ('institution', models.CharField(max_length=160)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Expected graduation year. Blank if ongoing.', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('status_note', models.CharField(blank=True, help_text='e.g. "Final year" or "Expected December 2026".', max_length=120)),
                ('result', models.CharField(blank=True, help_text='CGPA or grade. Stored but not shown unless enabled below.', max_length=40)),
                ('show_result', models.BooleanField(default=False, help_text='Display the result publicly.')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_year'],
            },
        ),
    ]
